// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.1
// source: stream.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StreamingClient is the client API for Streaming service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamingClient interface {
	ImgStream(ctx context.Context, opts ...grpc.CallOption) (Streaming_ImgStreamClient, error)
}

type streamingClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamingClient(cc grpc.ClientConnInterface) StreamingClient {
	return &streamingClient{cc}
}

func (c *streamingClient) ImgStream(ctx context.Context, opts ...grpc.CallOption) (Streaming_ImgStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Streaming_ServiceDesc.Streams[0], "/Streaming/ImgStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamingImgStreamClient{stream}
	return x, nil
}

type Streaming_ImgStreamClient interface {
	Send(*Image) error
	Recv() (*Result, error)
	grpc.ClientStream
}

type streamingImgStreamClient struct {
	grpc.ClientStream
}

func (x *streamingImgStreamClient) Send(m *Image) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamingImgStreamClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamingServer is the server API for Streaming service.
// All implementations must embed UnimplementedStreamingServer
// for forward compatibility
type StreamingServer interface {
	ImgStream(Streaming_ImgStreamServer) error
	mustEmbedUnimplementedStreamingServer()
}

// UnimplementedStreamingServer must be embedded to have forward compatible implementations.
type UnimplementedStreamingServer struct {
}

func (UnimplementedStreamingServer) ImgStream(Streaming_ImgStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ImgStream not implemented")
}
func (UnimplementedStreamingServer) mustEmbedUnimplementedStreamingServer() {}

// UnsafeStreamingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamingServer will
// result in compilation errors.
type UnsafeStreamingServer interface {
	mustEmbedUnimplementedStreamingServer()
}

func RegisterStreamingServer(s grpc.ServiceRegistrar, srv StreamingServer) {
	s.RegisterService(&Streaming_ServiceDesc, srv)
}

func _Streaming_ImgStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamingServer).ImgStream(&streamingImgStreamServer{stream})
}

type Streaming_ImgStreamServer interface {
	Send(*Result) error
	Recv() (*Image, error)
	grpc.ServerStream
}

type streamingImgStreamServer struct {
	grpc.ServerStream
}

func (x *streamingImgStreamServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamingImgStreamServer) Recv() (*Image, error) {
	m := new(Image)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Streaming_ServiceDesc is the grpc.ServiceDesc for Streaming service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Streaming_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Streaming",
	HandlerType: (*StreamingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ImgStream",
			Handler:       _Streaming_ImgStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "stream.proto",
}
