# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstream.proto\"!\n\x05Image\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x17\n\x06Result\x12\r\n\x05smoke\x18\x01 \x01(\x08\x32/\n\tStreaming\x12\"\n\tImgStream\x12\x06.Image\x1a\x07.Result\"\x00(\x01\x30\x01\x42\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stream_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\002./'
  _globals['_IMAGE']._serialized_start=16
  _globals['_IMAGE']._serialized_end=49
  _globals['_RESULT']._serialized_start=51
  _globals['_RESULT']._serialized_end=74
  _globals['_STREAMING']._serialized_start=76
  _globals['_STREAMING']._serialized_end=123
# @@protoc_insertion_point(module_scope)
